### ISSUE TITLE
Crash immediately when query is finished

### ISSUE THREAD

**Issue by cherrot** [xiaoyifang/goldendict#173]
version: `22.9.24.alpha.221017.82c700f1.r0.g02445aaf-1`  built from [ArchLinux AUR](https://aur.archlinux.org/packages/goldendict-webengine-git)

```
send dicts(finished): "a" : ("81ede02f38f5281de5dce1834076f8fe", "c42d4ef59daffeb78d324d363c5a97b4", "4eb901a014016950e216505fb3727c59", "691fece5582b52f0ee0dc8e8500d4a2b", "f89ea2a5d48a43b74689a5853c84ca32", "b6fa98f3817d771f3652975cc6fdcf90", "1680d7ec7eed9f7b36d1db0ced393a6b", "8312f649d91f1f28e264255be902dd26")
receive dicts, current word: "a" "a" : ("81ede02f38f5281de5dce1834076f8fe", "c42d4ef59daffeb78d324d363c5a97b4", "4eb901a014016950e216505fb3727c59", "691fece5582b52f0ee0dc8e8500d4a2b", "f89ea2a5d48a43b74689a5853c84ca32", "b6fa98f3817d771f3652975cc6fdcf90", "1680d7ec7eed9f7b36d1db0ced393a6b", "8312f649d91f1f28e264255be902dd26")
====reading 65536 bytes
====reading 65536 bytes
====reading 65536 bytes
====reading 17351 bytes
getResource: g
scheme: g
host: 7
/usr/include/c++/12.2.0/bits/stl_vector.h:1206: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::front() [with _Tp = char; _Alloc = std::allocator<char>; reference = char&]: Assertion '!this->empty()' failed.
[1]    182499 IOT instruction (core dumped)  goldendict
```

**Comment by xiaoyifang** [comment]
need more log

**Comment by cherrot** [comment]
After startup:
```
$ goldendict
"No favorities file found"
Load done

set inspected page to nullptr
getResource: g
scheme: g
host: l
In-place finish.

getResource: g
scheme: g
host: l
In-place finish.

====reading 2712 bytes
====reading 1706 bytes
article view loaded url: "gdlookup://localhost?word=(untitled)&blank=1" true
article view loaded url: "gdlookup://localhost?word=Welcome!&group=4294967295" true
libpng warning: iCCP: known incorrect sRGB profile
clipboard change , false ScanPopup(0x55ef48d1d580, name="ScanPopup")
clipboard change , false ScanPopup(0x55ef48d1d580, name="ScanPopup")
```

Now query for `hello`:
```
getResource: g
scheme: g
host: l
clear current dictionaries: "hello"
clear current dictionaries: "hello"
clear current dictionaries: "hello"
clear current dictionaries: "hello"
clear current dictionaries: "hello"
some body finished
one not finished.
some body finished
one not finished.
some body finished
one not finished.
some body finished
one not finished.
some body finished
one not finished.
some body finished
one not finished.
some body finished
one not finished.
some body finished
one not finished.
some body finished
one not finished.
some body finished
one not finished.
some body finished
one not finished.
some body finished
one not finished.
some body finished
one not finished.
some body finished
one finished.
erasing..
erase done..
one finished.
erasing..
erase done..
one not finished.
send dicts(updated): "hello" : ("798fa45b1e4a46014b5e8b14d5f0dea2", "ff56e2f82933dc366d5567c97823c154")
receive dicts, current word: "hello" "hello" : ("798fa45b1e4a46014b5e8b14d5f0dea2", "ff56e2f82933dc366d5567c97823c154")
some body finished
one finished.
erasing..
erase done..
one finished.
erasing..
erase done..
one finished.
erasing..
erase done..
one finished.
erasing..
erase done..
one finished.
erasing..
erase done..
one finished.
erasing..
erase done..
one finished.
erasing..
erase done..
one finished.
erasing..
erase done..
one finished.
erasing..
erase done..
one finished.
erasing..
erase done..
one finished.
erasing..
erase done..
one finished.
erasing..
erase done..
one finished.
erasing..
erase done..
one finished.
erasing..
erase done..
one finished.
erasing..
erase done..
one finished.
erasing..
erase done..
send dicts(finished): "hello" : ("81ede02f38f5281de5dce1834076f8fe", "4eb901a014016950e216505fb3727c59", "691fece5582b52f0ee0dc8e8500d4a2b", "b6fa98f3817d771f3652975cc6fdcf90", "1680d7ec7eed9f7b36d1db0ced393a6b", "8312f649d91f1f28e264255be902dd26")
receive dicts, current word: "hello" "hello" : ("81ede02f38f5281de5dce1834076f8fe", "4eb901a014016950e216505fb3727c59", "691fece5582b52f0ee0dc8e8500d4a2b", "b6fa98f3817d771f3652975cc6fdcf90", "1680d7ec7eed9f7b36d1db0ced393a6b", "8312f649d91f1f28e264255be902dd26")
====reading 65536 bytes
====reading 5881 bytes
getResource: g
scheme: g
host: 7
/usr/include/c++/12.2.0/bits/stl_vector.h:1206: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::front() [with _Tp = char; _Alloc = std::allocator<char>; reference = char&]: Assertion '!this->empty()' failed.
[1]    468480 IOT instruction (core dumped)  goldendict
```

FYI I'm using `swaywm` on Wayland, my `/etc/environment` is as follows:

```
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx

INPUT_METHOD=fcitx
SDL_IM_MODULE=fcitx
GLFW_IM_MODULE=ibus

SDL_VIDEODRIVER=wayland
QT_QPA_PLATFORM=wayland
XDG_CURRENT_DESKTOP=sway
XDG_SESSION_DESKTOP=sway
```

Do you need the core dumped file (11MB) ? I could upload it to somewhere.

**Comment by xiaoyifang** [comment]
yes, plz upload the core dump 
It will help to identify the cause

**Comment by cherrot** [comment]
Version: 22.9.24.alpha.221017.82c700f1.r1.g3561f804-1

core dump: https://github.com/cherrot/tmpfiles/blob/master/core.goldendict.1000.ea8808c2c5244a6a94863d5a7721d3f6.515656.1666272504000000.zst 

Thanks in advance!

**Comment by xiaoyifang** [comment]
currently I have no Archlinux environment ,wish someone can help.

can @cherrot  does this crash occured with any dictionaries or only crash with certain dictionary.

**Comment by xiaoyifang** [comment]
I guess it was the dictionary which has the id 798fa45b1e4a46014b5e8b14d5f0dea2   
you can check through the dictionary info and find out the dictionary.

**Comment by cherrot** [comment]
This is the first one in my dictionary list. I've moved it out of my dictionary folder, but the issue remains :( 

Later I'll give a test on my other desktop environments to see if there is any difference.

**Comment by xiaoyifang** [comment]
use the latest code and have a try again ,
I fixed a possible bug which maybe specially related to archlinux stl_vector.h

**Comment by bg2908** [comment]
The latest patch still crash for me.

But if I install from source with just `qmake-qt5 && make`, the binary work without issue.

Install from AUR and it start to crash

**Comment by xiaoyifang** [comment]
which qt version do you use

**Comment by xiaoyifang** [comment]
which qt version do you use when install with AUR

you can check goldendict- help  about。menu。

**Comment by bg2908** [comment]
> one possible reason is that the AUR does not use the latest commit on default.

I don't think so. It a git AUR so it automatic update to the latest git commit.
And this happen before your fix too. Install from AUR and it crash, compile from source and it work.

**Comment by xiaoyifang** [comment]
then it is most likely a AUR issue.  maybe report to AUR community.

**Comment by shenlebantongying** [comment]
I cannot reproduce any crashes.

`-git` packages need `--devel` flag like `yay -Syu --devel` to update btw. It will certainly pickup the latest commit from the default branch. 

<img src="https://user-images.githubusercontent.com/20123683/197678947-a8708825-0792-44c6-8f86-44673e6cd198.png" height="100" />

**Comment by epistularum** [comment]
> `-git` packages need `--devel` flag like `yay -Syu --devel` to update btw. It will certainly pickup the latest commit from the default branch.

I am not getting any update when doing "yay -Syu --devel" and still crashing.

![image](https://user-images.githubusercontent.com/34507493/197957210-c76ec471-d47c-47d3-8527-f2e4580482c1.png)

**Comment by xiaoyifang** [comment]
can you debug the application and paste the backtrace when crashed?

take a reference from 
https://stackoverflow.com/questions/4321184/help-for-gdb-debug-crash-logging

**Comment by epistularum** [comment]
@xiaoyifang First time using GDB, hopefully I did it correctly:
```
====reading 18438 bytes
getResource: "gico://bc501630ae0546a9d6e2dbc3e6aa97c5/dicticon.png"
scheme: "gico"
host: "bc501630ae0546a9d6e2dbc3e6aa97c5"
/usr/include/c++/12.2.0/bits/stl_vector.h:1206: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::front() [with _Tp = char; _Alloc = std::allocator<char>; reference = char&]: Assertion '!this->empty()' failed.

Thread 1 "goldendict" received signal SIGABRT, Aborted.
0x00007fffecaa164c in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007fffecaa164c in  () at /usr/lib/libc.so.6
#1  0x00007fffeca51958 in raise () at /usr/lib/libc.so.6
#2  0x00007fffeca3b53d in abort () at /usr/lib/libc.so.6
#3  0x00007fffebcd2112 in std::__glibcxx_assert_fail(char const*, int, char const*, char const*)
    (file=<optimized out>, line=<optimized out>, function=<optimized out>, condition=<optimized out>) at /usr/src/debug/gcc/libstdc++-v3/src/c++11/debug.cc:60
#4  0x000055555565a55a in  ()
#5  0x0000555555672f83 in  ()
#6  0x0000555555663ef8 in  ()
#7  0x000055555561fe1c in  ()
#8  0x00007fffee421c9c in  () at /usr/lib/libQt5WebEngineCore.so.5
#9  0x00007fffee4906e6 in  () at /usr/lib/libQt5WebEngineCore.so.5
#10 0x00007fffee40754b in  () at /usr/lib/libQt5WebEngineCore.so.5
#11 0x00007ffff04eb6ce in  () at /usr/lib/libQt5WebEngineCore.so.5
#12 0x00007ffff0b82dd4 in  () at /usr/lib/libQt5WebEngineCore.so.5
#13 0x00007ffff0b83561 in  () at /usr/lib/libQt5WebEngineCore.so.5
#14 0x00007ffff0b83561 in  () at /usr/lib/libQt5WebEngineCore.so.5
#15 0x00007ffff4b7297f in  () at /usr/lib/libQt5WebEngineCore.so.5
#16 0x00007fffffffce60 in  ()
#17 0x0000000000000000 in  ()
```

**Comment by xiaoyifang** [comment]
is this the backtrace when the application crashed?

**Comment by epistularum** [comment]
@xiaoyifang Yes.

**Comment by xiaoyifang** [comment]
the guess the gdb command should like something below
```
gdb goldendict
r
c
```
and search the word ,application crashed.
back to console and put
```
bt
```



not seeing anything useful in the backtrace,

can you try to reduce your dictionaries and have some try.

**Comment by xiaoyifang** [comment]
@epistularum just submit a commit  971909177662ac78fad6fce5cf206f3a32e8c997

do not know if it was the cause.

**Comment by epistularum** [comment]
@xiaoyifang Same issue. As you have said this is most than probably an issue with the AUR PKGBUILD as I do not have this issue when building from source (I get other issues but that might just be because I'm compiling it wrong, perhaps missing some dependencies?. I am not used to compiling from source).

For reference, the AUR PKGBUILD looks like this:

```
# Contributor: VirtualTam <virtualtam@flibidi.net>
# Contributor: Eugene Yudin aka Infy <Eugene dot Yudin at gmail dot com>
# Contributor: aksr <aksr at t-com dot me>
# Maintainer: slbtty <shenlebantongying@gmail.com>

pkgname=goldendict-webengine-git
pkgver=22.9.24.alpha.220930.ca7fc1c2.r71.g6742321a
pkgrel=1
pkgdesc="A feature-rich dictionary lookup program, supporting multiple dictionary formats."
arch=('i686' 'x86_64')
url="https://github.com/xiaoyifang/goldendict"
url="http://goldendict.org/"
license=('GPL3')
depends=('ffmpeg' 'hunspell' 'libao' 'libvorbis' 'libxtst' 'lzo' 'zlib' 'xz' 'libeb' 'opencc'
	 'qt5-svg' 'qt5-tools' 'qt5-x11extras' 'qt5-multimedia' 'qt5-webengine')
makedepends=('git')
conflicts=('goldendict' 'goldendict-git' 'goldendict-svn' 'goldendict-git-opt')
provides=('goldendict')
replaces=('goldendict-svn' 'goldendict-git-opt')
source=("$pkgname::git+https://github.com/xiaoyifang/goldendict.git")
md5sums=('SKIP')

pkgver() {
	cd "$srcdir/$pkgname"
	git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
}

prepare() {
	cd "$srcdir/$pkgname"
}

build(){
	cd "$srcdir/$pkgname"
	qmake-qt5 "CONFIG+=release" "CONFIG+=zim_support" "CONFIG+=chinese_conversion_support" PREFIX="/usr" goldendict.pro
	make
}

package() {
	cd "$srcdir/$pkgname"
	make INSTALL_ROOT="$pkgdir" install
}
```

**Comment by xiaoyifang** [comment]
same error as 
https://github.com/polybar/polybar/issues/2416

**Comment by epistularum** [comment]
This worked! I'm posting a comment on the aur page. Thank you very much.

**Comment by Lraxer** [comment]
> same error as [polybar/polybar#2416](https://github.com/polybar/polybar/issues/2416)
> 
> ![image](https://user-images.githubusercontent.com/105986/197989864-5df55e2d-c013-4eef-885f-744204327468.png)

This solution works for me. I use `makepkg -cs CXXFLAGS="" ` and `pacman -U` to build and install the package manually, and I find there's no crash anymore, so it's not a goldendict issue. Thanks for your help!

**Comment by shenlebantongying** [comment]
Overriding `CXXFLAGS=""` is not a solution or root cause. It is a workaround. Getting rid of all CXXFLAGS also disables -O2.

This is my current `/etc/makepkg.conf` but i cannot reproduce a crash
```
#########################################################################
# ARCHITECTURE, COMPILE FLAGS
#########################################################################
#
CARCH="x86_64"
CHOST="x86_64-pc-linux-gnu"

#-- Compiler and Linker Flags
#CPPFLAGS=""
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
LTOFLAGS="-flto=auto"
```

**Comment by shenlebantongying** [comment]
I removed `GLIBCXX_ASSERTIONS` by
```
echo "QMAKE_CXXFLAGS += -U_GLIBCXX_ASSERTIONS" >> goldendict.pro
```

Can someone confirm if this stops crash when installing from AUR?

https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=goldendict-webengine-git&id=8b2827d998522a229ad6c878a4d230128b51b45e

**Comment by cherrot** [comment]
@shenlebantongying I can confirm it is fixed on my laptop. Thanks!

**Comment by bg2908** [comment]
It fixed on my end too

**Comment by xiaoyifang** [comment]
> -U_GLIBCXX_ASSERTIONS

should I include this flag in the goldendict.pro directly?

**Comment by shenlebantongying** [comment]
Copied from <https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_macros.html>

_GLIBCXX_ASSERTIONS

Undefined by default. When defined, enables extra error checking in the form of precondition assertions, such as bounds checking in strings and null pointer checks when dereferencing smart pointers. 

Also

_GLIBCXX_DEBUG

Undefined by default. When defined, compiles user code using the [debug mode](https://gcc.gnu.org/onlinedocs/libstdc++/manual/debug_mode.html). When defined, _GLIBCXX_ASSERTIONS is defined automatically, so all the assertions enabled by that macro are also enabled in debug mode.

---

_GLIBCXX_ASSERTIONS adds some checks from GCC's debug mode. It might expose an unobvious "bug" which probably isn't specific to Linux.

However, my dictionaries won't trigger any crashes to let me debug it :(

I don't think we should remove this flag somehow.

**Comment by xiaoyifang** [comment]
I think this bug was triggered by some certain dictionaries and strict gxx checking both.
