### ISSUE TITLE
Bug? Esc key to close main Goldendict window doesn't work after hotkey

### ISSUE THREAD

**Issue by razielaka** [xiaoyifang/goldendict#310]
First, thanks for continuing the development!

Problem: After searching a word using the hotkey (I changed it to ctrl + \ but the original ctrl+c+c doesn't work consistently either) (and the "send translated word to main windows" and "ESC key hides main window" features on), the Esc key does not work. In order to make it work, a mouse click on the main window is necessary first (or using the hotkey again, sometimes twice). Connected to this problem, it is also not possible to immediately type in a new word to search for without first clicking inside the main window.

Expected behavior: Pressing Esc key after opening the main window with shortcut key (such as ctrl+\) should close the windows. Typing should be directly entered into the search box.

Software: Windows 11 and Goldendict v22.12.24-alpha.230109.b47a6acf (though previous versions had the same problem)

Thanks again for your great work!

**Comment by xiaoyifang** [comment]
> "ESC key hides main window"

esc is not a global key ,which means in order to work ,the gd must be activated.



> I changed it to ctrl + \ but the original ctrl+c+c doesn't work consistently

this global hot key must start with `Ctrl+C` ,as it depends on system clipboard to work.
start the gd as administrator should solve this issue.

**Comment by razielaka** [comment]
> esc is not a global key ,which means in order to work ,the gd must be activated

Certainly gd must be active to use the ESC key. Why would anyone want to close the window when it isn't even active? However, when the window is active and in the foreground, it still does not work unless I click on the window first.



> this global hot key must start with `Ctrl+C` ,as it depends on system clipboard to work

I don't have a problem with the global hotkey itself. It works fine. I use ctrl+c to copy the word before using the hotkey. However, even using the default hotkey doesn't fix the ESC key problem. The problem is that after the word is looked up in GD, I cannot press ESC to close the GD window (unless I click inside the window first). This makes the press ESC button to close the window useless since you have to click. It's easier to just press Alt+F4 (which does work). Perhaps the window isn't active, even though it should be active immediately after a word is looked up.
